# Allows the user guest (administrator permissions) to connect via remote and not only from localhost
# For virtual development devices, we want to connect to the container's RabbitMQ from our hostsystem. 
loopback_users = none
