
query getDeviceInfoBasic($id: UUID!) {
    device(id: $id) {
        id
        serialNumber
        deviceName
        description
        deviceStatus {
            lastAppstoreActivity
            lastMessagingActivity
            lastHubEndpoint
            lastUptime
            lastUplinkSignalContent
        }
        deviceModelRevision {
            id
            deviceModel {
                deviceType {
                    deviceTypeName
                }
                modelName
                architecture
            }
            revision
            deviceModelRevisionBridgeApps {
                app {
                    id
                    appName
                    description
                }
            }
        }
        pendingActions {
            pendingActionCount
            items {
                appName
                deltaFileSize
                downloadSize
                installedRevision
                installedVersion
                isCoreApp
                pendingActionName
                targetRevision
                targetVersion
            }
        }
        connectedDevice{
            id
            serialNumber
            deviceName
        }
        connectedDevices{
            id
            serialNumber
            deviceName
            deviceModelRevision {
                deviceModel {
                    modelName
                    architecture
                }
                revision
            }

        }
        deviceSnap {
            deviceTpmEkPublicKey
            uplinkMode
        }
        assetId
        asset {
          id
        }
    }
}
