query GetDeviceModelRevisionInfoById($id: UUID!) {
  deviceModelRevision(id: $id) {
    id
    deviceModelId
    revision
    isTpmRequired
    isPreRegistrationRequired
    uploadMessage
    modelAssertionId
    deviceModel {
      modelName
      architecture
      deviceType {
        deviceTypeName
      }
    }
    deviceModelRevisionBridgeApps {
      app {
        id
        appName
        summary
        appSnap {
          snapBase
          snapType {
            id
            snapTypeName
          }
        }
      }
    }
  }
}
