; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ML!PA M2CP"
#define MyAppVersion "PLACEHOLDER"
#define MyAppPublisher "ML!PA GmbH"
#define MyAppURL "https://www.ml-pa.com/"
#define MyAppExeName "m2cp.exe"
#define CmdHelp "Use 'm2cp help' for list of m2cp-commands."

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{177EDA31-C152-4DE8-BC6B-982FB025034C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesInstallIn64BitMode=x64
DefaultDirName={autopf}\ML!PA\M2CP
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=.\build
OutputBaseFilename=m2cp-setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: ".\stage\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ".\stage\docs\*"; DestDir: "{app}\docs"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: ".\assets\favicon.ico"; DestDir: "{app}"; Flags: ignoreversion


[Icons]
Name: "{autoprograms}\{#MyAppName} Terminal"; Filename: "cmd.exe"; Parameters: "/k set PATH={app};%PATH% & cd /d ""%HOMEDRIVE%%HOMEPATH%"" & ""{app}\{#MyAppExeName}"" & echo. & echo {#CmdHelp}"; WorkingDir: "{app}"; IconFilename: "{app}\favicon.ico"
Name: "{autodesktop}\{#MyAppName} Terminal"; Filename: "cmd.exe"; Parameters: "/k set PATH={app};%PATH% & cd /d ""%HOMEDRIVE%%HOMEPATH%"" & ""{app}\{#MyAppExeName}"" & echo. & echo {#CmdHelp}"; Tasks: desktopicon; WorkingDir: "{app}"; IconFilename: "{app}\favicon.ico"
Name: "{autoprograms}\{#MyAppName} Documentation"; Filename: "{app}\docs\index.html"; IconFilename: "{app}\favicon.ico"
Name: "{autodesktop}\{#MyAppName} Documentation"; Filename: "{app}\docs\index.html"; Tasks: desktopicon; IconFilename: "{app}\favicon.ico"

[Registry]
Root: "HKLM"; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "Path"; ValueData: "{olddata};{app}"; Flags: preservestringtype

[Run]
;Filename: "cmd.exe"; Parameters: "/k set PATH={app};%PATH% & cd /d ""%HOMEDRIVE%%HOMEPATH%"" & ""{app}\{#MyAppExeName}"" & echo. & echo Type commands and press Enter..."; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "cmd.exe"; Parameters: "/k set PATH={app};%PATH% & cd /d ""%HOMEDRIVE%%HOMEPATH%"" & ""{app}\{#MyAppExeName}"" & echo. & echo {#CmdHelp}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


