package suit

import (
	"github.com/stretchr/testify/assert"
	"go.uber.org/goleak"
	"testing"
)

func TestNewInstallDigestFromBytes(t *testing.T) {
	defer goleak.VerifyNone(t)

	firmware := []byte("test firmware")
	i, err := NewInstallDigestFromBytes(firmware)
	assert.NoError(t, err)
	assert.NotNil(t, i)

	assert.Equal(t, "sha256", i.AlgorithmID)
	assert.Equal(t, "sha256:ef7dbbe324eab86ab67a198f95b46d7fbf79d5ebf4a4c2c72fc7da9d724aac96", i.String())
}

func TestNewManifestSimple(t *testing.T) {
	defer goleak.VerifyNone(t)

	// as generated with
	// ```
	// $ python3 ./dist/tools/suit/gen_manifest.py --urlroot "abc" --seqnr "123" --output /tmp/test.json \
	//   --uuid-vendor "efg" --uuid-class "hij" one two
	// ```
	jsonString := `{
    "manifest-version": 1,
    "manifest-sequence-number": 123,
    "components": [
        {
            "install-id": [
                "00"
            ],
            "vendor-id": "57ae6c2d2b675502816ec7c05bf62142",
            "class-id": "bf552cfa82155d01a0bd2a0b035b308c",
            "file": "one",
            "uri": "abc/one",
            "bootable": false
        },
        {
            "install-id": [
                "00"
            ],
            "vendor-id": "57ae6c2d2b675502816ec7c05bf62142",
            "class-id": "bf552cfa82155d01a0bd2a0b035b308c",
            "file": "two",
            "uri": "abc/two",
            "bootable": false
        }
    ]
}`

	m, err := NewManifestCreationInputFromFiles("efg", "hij", 123, []string{"one", "two"}, "abc")
	assert.NoError(t, err)
	assert.NotNil(t, m)
	//fmt.Println(m.String())
	assert.Equal(t, jsonString, m.String())
}

func TestNewManifestMoreDetailedAddresses(t *testing.T) {
	defer goleak.VerifyNone(t)

	// as generated by:
	// ```
	// python3 ./dist/tools/suit/gen_manifest.py --urlroot "http://example.com/files" --seqnr "123" \
	//   --output /tmp/test.2json --uuid-vendor "ml-pa.com" --uuid-class "example-class" \
	//   firmware.bin:1024:01 boot.img:4096
	// ```
	jsonString := `{
    "manifest-version": 1,
    "manifest-sequence-number": 543,
    "components": [
        {
            "install-id": [
                "01"
            ],
            "vendor-id": "95b2a5c5125f5a84ada0116139c70207",
            "class-id": "728a11d9d8f452239475e030105066a8",
            "file": "firmware.bin",
            "uri": "http://example.com/files/firmware.bin",
            "bootable": false,
            "offset": 1024
        },
        {
            "install-id": [
                "00"
            ],
            "vendor-id": "95b2a5c5125f5a84ada0116139c70207",
            "class-id": "728a11d9d8f452239475e030105066a8",
            "file": "boot.img",
            "uri": "http://example.com/files/boot.img",
            "bootable": false,
            "offset": 4096
        }
    ]
}`

	m, err := NewManifestCreationInputFromFiles("ml-pa.com", "example-class", 543,
		[]string{"firmware.bin:1024:01", "boot.img:4096"},
		"http://example.com/files")
	assert.NoError(t, err)
	assert.NotNil(t, m)
	// fmt.Println(m.String())
	assert.Equal(t, jsonString, m.String())
}

func TestNewManifestWithHexAddresses(t *testing.T) {
	defer goleak.VerifyNone(t)

	// as generated by:
	// ```
	// python3 ./dist/tools/suit/gen_manifest.py --urlroot "http://example.com/files" --seqnr "123" \
	//   --output /tmp/test.2json --uuid-vendor "ml-pa.com" --uuid-class "example-class" \
	//   firmware.bin:0x1024:01 boot.img:0x10000
	// ```
	jsonString := `{
    "manifest-version": 1,
    "manifest-sequence-number": 123,
    "components": [
        {
            "install-id": [
                "01"
            ],
            "vendor-id": "95b2a5c5125f5a84ada0116139c70207",
            "class-id": "728a11d9d8f452239475e030105066a8",
            "file": "firmware.bin",
            "uri": "http://example.com/files/firmware.bin",
            "bootable": false,
            "offset": 4132
        },
        {
            "install-id": [
                "00"
            ],
            "vendor-id": "95b2a5c5125f5a84ada0116139c70207",
            "class-id": "728a11d9d8f452239475e030105066a8",
            "file": "boot.img",
            "uri": "http://example.com/files/boot.img",
            "bootable": false,
            "offset": 65536
        }
    ]
}`

	m, err := NewManifestCreationInputFromFiles("ml-pa.com", "example-class", 123,
		[]string{"firmware.bin:0x1024:01", "boot.img:0x10000"},
		"http://example.com/files")
	assert.NoError(t, err)
	assert.NotNil(t, m)
	// fmt.Println(m.String())
	assert.Equal(t, jsonString, m.String())
}
