# @genqlient(omitempty: true)
mutation UpdateDeploymentGroup(
    $id: UUID!
    $name: String
    $description: String
    $autoUpdateModeId: UUID
    $isDeltaUpdateOnly: Boolean
) {
    updateDeploymentGroups(
        deploymentGroups: [
            {
                id: $id
                name: $name
                description: $description
                autoUpdateModeId: $autoUpdateModeId
                isDeltaUpdateOnly: $isDeltaUpdateOnly
            }
        ]
    ) {
        id
        isDeltaUpdateOnly
    }
}
